/**
 * File responsibility: Custom React hook.
 * Main responsibilities:
 * - Keep presentation, state orchestration, and display helpers separated so React components stay reusable.
 * - Main file role: useReportData should manage state transitions, side effects, and derived values while keeping UI files thin.
 * - Prefer extending behaviour by adding small helpers or sibling modules instead of growing one large file.
 * Maintenance notes:
 * - Keep this file focused on one layer of responsibility.
 * - Prefer composition and small helpers over repeated inline logic.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { generateReport, getReport, qaReport } from '../api/reportApi.js';

const buildStatus = (variant, title, message) => ({ variant, title, message });

const isMissingReportError = (error) => {
  const message = String(error?.message || '').toLowerCase();
  return message.includes('report not found') || message.includes('no report exists');
};

export function useReportData(sessionId) {
  const [reportData, setReportData] = useState(null);
  const [status, setStatus] = useState(buildStatus('info', 'Report', 'Generate a structured report for this session.'));
  const [loading, setLoading] = useState(false);
  const hasAutoGeneratedRef = useRef(false);

  const loadReport = useCallback(async ({ autoGenerateIfMissing = false } = {}) => {
    try {
      const data = await getReport(sessionId);
      setReportData(data);
      setStatus(buildStatus('success', 'Report loaded', `Status: ${data.latestStatus || 'ready'}`));
      return data;
    } catch (error) {
      if (autoGenerateIfMissing && !hasAutoGeneratedRef.current && isMissingReportError(error)) {
        hasAutoGeneratedRef.current = true;
        setStatus(buildStatus('info', 'Generating report', 'No saved report was found, so a fresh one is being generated now.'));
        await generateReport({ sessionId });
        return loadReport({ autoGenerateIfMissing: false });
      }

      setReportData(null);
      setStatus(buildStatus('info', 'No report yet', error.message || 'Generate a report to view it here.'));
      return null;
    }
  }, [sessionId]);

  useEffect(() => {
    setLoading(true);
    loadReport({ autoGenerateIfMissing: true })
      .finally(() => setLoading(false));
  }, [loadReport]);

  const runReportAction = useCallback(async ({ action, successStatus, failureTitle }) => {
    setLoading(true);
    try {
      const result = await action();
      if (result?.stored || result?.report || result?.qaResult) {
        setReportData(result.stored || result);
      }
      setStatus(successStatus);
      await loadReport();
    } catch (error) {
      setStatus(buildStatus('error', failureTitle, error.message || 'Something went wrong.'));
    } finally {
      setLoading(false);
    }
  }, [loadReport]);

  const handleGenerate = useCallback(() => runReportAction({
    action: () => generateReport({ sessionId }),
    successStatus: buildStatus('success', 'Report generated', 'A new structured report is ready.'),
    failureTitle: 'Generation failed',
  }), [runReportAction, sessionId]);

  const handleQa = useCallback(() => runReportAction({
    action: () => qaReport({ sessionId }),
    successStatus: buildStatus('success', 'QA completed', 'Report QA flags were refreshed.'),
    failureTitle: 'QA failed',
  }), [runReportAction, sessionId]);

  return {
    reportData,
    status,
    loading,
    handleGenerate,
    handleQa,
  };
}
