/**
 * File responsibility: Custom React hook.
 * Main responsibilities:
 * - Keep presentation, state orchestration, and display helpers separated so React components stay reusable.
 * - Main file role: useReportData should manage state transitions, side effects, and derived values while keeping UI files thin.
 * - Prefer extending behaviour by adding small helpers or sibling modules instead of growing one large file.
 * Maintenance notes:
 * - Keep this file focused on one layer of responsibility.
 * - Prefer composition and small helpers over repeated inline logic.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { generateReport, getReport, qaReport, exportReport, downloadReportFile, generateReportPDF } from '../api/reportApi.js';
import { downloadSessionRecording, getSessionRecordingStatus } from '../api/recordingApi.js';
import { EXPORT_AUDIT_TIMEOUT_MS } from '../constants/reportConstants.js';
import { buildStatus, isMissingReportError, withTimeout, formatReportAsText } from '../utils/reportHelpers.js';

const RECORDING_STATUS_POLL_INTERVAL_MS = 2000;
const RECORDING_STATUS_POLL_TIMEOUT_MS = 60000;

const toRecordingStatusState = (result = {}) => ({
  state: result?.available ? 'ready' : 'missing',
  available: Boolean(result?.available),
  error: null,
});

export function useReportData(sessionId) {
  const [reportData, setReportData] = useState(null);
  const [status, setStatus] = useState(buildStatus('info', 'Report', 'Generate a structured report for this session.'));
  const [loading, setLoading] = useState(false);
  const [recordingStatus, setRecordingStatus] = useState({ state: 'checking', available: false, error: null });
  const hasAutoGeneratedRef = useRef(false);

  const loadReport = useCallback(async ({ autoGenerateIfMissing = false } = {}) => {
    try {
      const data = await getReport(sessionId);
      setReportData(data);
      setStatus(buildStatus('success', 'Report loaded', `Status: ${data.latestStatus || 'ready'}`));
      return data;
    } catch (error) {
      if (autoGenerateIfMissing && !hasAutoGeneratedRef.current && isMissingReportError(error)) {
        hasAutoGeneratedRef.current = true;
        setStatus(buildStatus('info', 'Generating report', 'No saved report was found, so a fresh one is being generated now.'));
        await generateReport({ sessionId });
        return loadReport({ autoGenerateIfMissing: false });
      }

      setReportData(null);
      setStatus(buildStatus('info', 'No report yet', error.message || 'Generate a report to view it here.'));
      return null;
    }
  }, [sessionId]);

  useEffect(() => {
    setLoading(true);
    loadReport({ autoGenerateIfMissing: true })
      .finally(() => setLoading(false));
  }, [loadReport]);

  useEffect(() => {
    let cancelled = false;
    let timer = null;
    const startedAt = Date.now();

    const clearPollTimer = () => {
      if (!timer) return;
      window.clearTimeout(timer);
      timer = null;
    };

    const scheduleNextCheck = (callback) => {
      const elapsedMs = Date.now() - startedAt;
      const remainingMs = RECORDING_STATUS_POLL_TIMEOUT_MS - elapsedMs;
      if (remainingMs <= 0) return;
      timer = window.setTimeout(callback, Math.min(RECORDING_STATUS_POLL_INTERVAL_MS, remainingMs));
    };

    const loadRecordingStatus = async () => {
      try {
        const result = await getSessionRecordingStatus(sessionId);
        if (cancelled) return;

        const nextStatus = toRecordingStatusState(result);
        setRecordingStatus(nextStatus);

        if (!nextStatus.available) {
          scheduleNextCheck(loadRecordingStatus);
        }
      } catch (error) {
        if (cancelled) return;
        setRecordingStatus({
          state: 'failed',
          available: false,
          error: error.message || 'Could not check MP3 recording status.',
        });
      }
    };

    setRecordingStatus({ state: 'checking', available: false, error: null });
    loadRecordingStatus();

    return () => {
      cancelled = true;
      clearPollTimer();
    };
  }, [sessionId]);

  const runReportAction = useCallback(async ({ action, successStatus, failureTitle }) => {
    setLoading(true);
    try {
      const result = await action();
      if (result?.stored || result?.report || result?.qaResult) {
        setReportData(result.stored || result);
      }
      setStatus(successStatus(result));
      await loadReport();
    } catch (error) {
      setStatus(buildStatus('error', failureTitle, error.message || 'Something went wrong.'));
    } finally {
      setLoading(false);
    }
  }, [loadReport]);

  const handleGenerate = useCallback(() => runReportAction({
    action: () => generateReport({ sessionId }),
    successStatus: () => buildStatus('success', 'Report generated', 'A new structured report is ready.'),
    failureTitle: 'Generation failed',
  }), [runReportAction, sessionId]);

  const handleQa = useCallback((userPrompt = '') => runReportAction({
    action: () => qaReport({ sessionId, userPrompt }),
    successStatus: (result = {}) => buildStatus(
      'success',
      result.rewriteApplied ? 'QA rewrite completed' : 'QA completed',
      result.rewriteApplied ? 'The report was rewritten with your prompt and QA was refreshed.' : 'Report QA flags were refreshed.'
    ),
    failureTitle: 'QA failed',
  }), [runReportAction, sessionId]);

  const handleExport = useCallback(async (format = 'json') => {
    setLoading(true);
    setStatus(buildStatus('info', 'Preparing export', `Preparing ${String(format).toUpperCase()} download...`));

    try {
      if (!reportData) {
        setStatus(buildStatus('error', 'Export failed', 'No report data available to export.'));
        return;
      }

      if (format === 'pdf') {
        await generateReportPDF(reportData);
        setStatus(buildStatus('success', 'Report exported', 'Report downloaded as PDF file.'));
        return;
      }

      const content = format === 'json'
        ? JSON.stringify(reportData, null, 2)
        : formatReportAsText(reportData);

      downloadReportFile({ content, sessionId, format });

      try {
        await withTimeout(
          exportReport({ sessionId, format }),
          EXPORT_AUDIT_TIMEOUT_MS,
          'Export audit timed out. The file was downloaded, but the server did not confirm the export record.'
        );
        setStatus(buildStatus('success', 'Report exported', `Report downloaded as ${format.toUpperCase()} file.`));
      } catch (auditError) {
        setStatus(buildStatus(
          'info',
          'Report downloaded',
          auditError.message || 'The file was downloaded, but the server export record could not be saved.'
        ));
      }
    } catch (error) {
      setStatus(buildStatus('error', 'Export failed', error.message || 'Could not export the report.'));
    } finally {
      setLoading(false);
    }
  }, [sessionId, reportData]);


  const handleDownloadRecording = useCallback(async () => {
    setLoading(true);
    try {
      await downloadSessionRecording(sessionId);
      setStatus(buildStatus('success', 'MP3 downloaded', 'Voice recording downloaded as an MP3 file.'));
    } catch (error) {
      setStatus(buildStatus('error', 'MP3 download failed', error.message || 'No MP3 recording is available for this session yet.'));
    } finally {
      setLoading(false);
    }
  }, [sessionId]);

  return {
    reportData,
    status,
    loading,
    handleGenerate,
    handleQa,
    handleExport,
    handleDownloadRecording,
    recordingStatus,
  };
}
