import { RETRIEVAL_OBJECTIVES } from '../../constants/retrievalObjectives.js';
import { RETRIEVAL_SOURCES } from './retrievalSourceRegistry.js';

const unique = (items = []) => [...new Set(items.filter(Boolean))];

export const selectRetrievalSources = ({ objective, preferredSources = [] } = {}) => {
  const base = {
    [RETRIEVAL_OBJECTIVES.BOOTSTRAP_INTERVIEW_CONTEXT]: [
      RETRIEVAL_SOURCES.GLOBAL_QUESTION_BANK,
      RETRIEVAL_SOURCES.GLOBAL_BEHAVIOURAL_BANK,
      RETRIEVAL_SOURCES.SESSION_INTERVIEW_PLAN,
      RETRIEVAL_SOURCES.SESSION_PREPARED_QUESTION_POOL,
      RETRIEVAL_SOURCES.SESSION_JD,
      RETRIEVAL_SOURCES.SESSION_CV,
      RETRIEVAL_SOURCES.SESSION_MATCH,
      RETRIEVAL_SOURCES.SESSION_TRANSCRIPT,
    ],
    [RETRIEVAL_OBJECTIVES.VALIDATE_CANDIDATE_CLAIM]: [
      RETRIEVAL_SOURCES.SESSION_MATCH,
      RETRIEVAL_SOURCES.SESSION_CV,
      RETRIEVAL_SOURCES.SESSION_TRANSCRIPT,
      RETRIEVAL_SOURCES.SESSION_JD,
    ],
    [RETRIEVAL_OBJECTIVES.FIND_ROLE_SPECIFIC_QUESTION]: [
      RETRIEVAL_SOURCES.SESSION_JD,
      RETRIEVAL_SOURCES.SESSION_MATCH,
      RETRIEVAL_SOURCES.SESSION_PREPARED_QUESTION_POOL,
      RETRIEVAL_SOURCES.GLOBAL_QUESTION_BANK,
      RETRIEVAL_SOURCES.GLOBAL_BEHAVIOURAL_BANK,
    ],
    [RETRIEVAL_OBJECTIVES.COLLECT_REPORT_EVIDENCE]: [
      RETRIEVAL_SOURCES.SESSION_MATCH,
      RETRIEVAL_SOURCES.SESSION_TRANSCRIPT,
      RETRIEVAL_SOURCES.SESSION_PREPARED_QUESTION_POOL,
      RETRIEVAL_SOURCES.SESSION_JD,
      RETRIEVAL_SOURCES.SESSION_CV,
      RETRIEVAL_SOURCES.SESSION_DECISIONS,
    ],
    [RETRIEVAL_OBJECTIVES.COVER_UNASKED_REQUIREMENT]: [
      RETRIEVAL_SOURCES.SESSION_JD,
      RETRIEVAL_SOURCES.SESSION_MATCH,
      RETRIEVAL_SOURCES.SESSION_PREPARED_QUESTION_POOL,
      RETRIEVAL_SOURCES.GLOBAL_QUESTION_BANK,
      RETRIEVAL_SOURCES.SESSION_TRANSCRIPT,
    ],
  };

  return unique([...(base[objective] || base[RETRIEVAL_OBJECTIVES.BOOTSTRAP_INTERVIEW_CONTEXT]), ...preferredSources]);
};
