export const TECHNICAL_SKILL_FAMILIES = {
  softwareDevelopment: [
    ['C#', ['c#', 'c sharp']],
    ['.NET', ['.net', 'dotnet', 'dot net']],
    ['.NET Web API', ['.net web api']],
    ['ASP.NET', ['asp.net', 'asp net']],
    ['MVC', ['mvc', 'model-view-controller']],
    ['JavaScript', ['javascript', 'js']],
    ['TypeScript', ['typescript', 'ts']],
    ['HTML', ['html', 'html5']],
    ['CSS', ['css']],
    ['React', ['react', 'reactjs', 'react.js']],
    ['Vue', ['vue', 'vue.js']],
    ['Angular', ['angular']],
    ['Node.js', ['node.js', 'node js', 'node']],
    ['Java', ['java']],
    ['Python', ['python']],
    ['PHP', ['php']],
    ['REST APIs', ['rest api', 'rest apis', 'restful api', 'restful apis']],
    ['GraphQL', ['graphql']],
    ['GitHub', ['github']],
    ['Git', ['git']],
    ['GitHub Actions', ['github actions']],
    ['Figma', ['figma']],
    ['Storybook', ['storybook']],
    ['Shopify', ['shopify']],
    ['eCommerce', ['ecommerce', 'e-commerce']],
    ['OAuth', ['oauth']],
    ['WPF', ['wpf']],
  ],
  data: [
    ['SQL', ['sql', 'structured query language']],
    ['PostgreSQL', ['postgresql', 'postgres']],
    ['MySQL', ['mysql']],
    ['Excel', ['excel']],
    ['Power BI', ['power bi', 'powerbi']],
    ['Power Query', ['power query']],
    ['Snowflake', ['snowflake']],
    ['Tableau', ['tableau']],
    ['ArcGIS', ['arcgis', 'esri']],
    ['Geospatial Analytics', ['geospatial', 'spatial data', 'geospatial analytics']],
    ['Data Cleaning', ['data cleaning', 'data cleansing']],
    ['Data Transformation', ['data transformation', 'data wrangling']],
    ['ETL', ['etl']],
    ['Big Data Pipelines', ['big data pipelines', 'end to end with big data pipelines']],
    ['Dashboarding', ['dashboarding', 'dashboards']],
    ['Reporting', ['reporting', 'reports']],
    ['Statistics', ['statistics', 'statistical analysis', 'statistical methodologies']],
    ['Regression', ['regression']],
    ['Clustering', ['clustering']],
    ['Classification', ['classification']],
    ['Pandas', ['pandas']],
    ['NumPy', ['numpy']],
    ['SciPy', ['scipy']],
    ['Jupyter', ['jupyter']],
    ['Graph Datasets', ['graph datasets', 'graph dataset']],
    ['Spark', ['spark', 'apache spark']],
    ['Airflow', ['airflow', 'apache airflow']],
    ['dbt', ['dbt']],
    ['Data Modelling', ['data modelling', 'data modeling', 'dimensional modelling', 'dimensional modeling', 'dv2', 'data vault 2.0']],
    ['Semantic Layers', ['semantic layer', 'semantic layers']],
    ['Databricks', ['databricks']],
    ['Kafka', ['kafka', 'apache kafka']],
    ['Redshift', ['redshift', 'amazon redshift']],
    ['Data Pipelines', ['data pipelines', 'data pipeline']],
    ['Data Platforms', ['data platforms', 'data platform']],
    ['Data Governance', ['data governance']],
    ['Data Quality', ['data quality']],
    ['ADF', ['adf', 'azure data factory']],
  ],
  aiMl: [
    ['Machine Learning', ['machine learning', 'ml']],
    ['Deep Learning', ['deep learning']],
    ['PyTorch', ['pytorch']],
    ['TensorFlow', ['tensorflow']],
    ['Keras', ['keras']],
    ['LLM', ['llm', 'large language model', 'large language models']],
    ['Prompt Engineering', ['prompt engineering']],
    ['RAG', ['rag', 'retrieval augmented generation']],
    ['Embeddings', ['embedding', 'embeddings']],
    ['Vector Search', ['vector search', 'vector database']],
    ['Semantic Retrieval', ['semantic retrieval']],
    ['NLP', ['nlp', 'natural language processing']],
    ['Model Deployment', ['model deployment', 'model serving']],
    ['Model Evaluation', ['model evaluation', 'evals']],
    ['AI APIs', ['ai apis', 'openai', 'azure openai']],
    ['Agentic Workflows', ['agentic workflows', 'agentic workflow']],
    ['Automation', ['automation', 'automations']],
    ['Feature Engineering', ['feature engineering']],
    ['MLOps', ['mlops']],
    ['Fine-tuning', ['fine tuning', 'fine-tuning']],
  ],
  itInfrastructure: [
    ['Windows Server', ['windows server']],
    ['Linux', ['linux']],
    ['Active Directory', ['active directory']],
    ['Networking', ['networking', 'tcp/ip', 'dns', 'dhcp', 'routing', 'switching', 'network support']],
    ['AWS', ['aws', 'amazon web services']],
    ['Azure', ['azure']],
    ['GCP', ['gcp', 'google cloud']],
    ['Cloud Infrastructure', ['cloud infrastructure', 'cloud']],
    ['Hardware Support', ['hardware support', 'hardware setup']],
    ['Software Troubleshooting', ['software troubleshooting']],
    ['Troubleshooting', ['troubleshooting']],
    ['Incident Management', ['incident management']],
    ['Cybersecurity', ['cybersecurity', 'security monitoring']],
    ['Access Control', ['access control', 'iam']],
    ['VPN', ['vpn']],
    ['Firewalls', ['firewalls', 'firewall']],
    ['n8n', ['n8n']],
    ['Make', ['make']],
    ['Ticketing Systems', ['ticketing system', 'ticketing systems', 'service desk']],
  ],
  commonEngineering: [
    ['Agile', ['agile']],
    ['Scrum', ['scrum']],
    ['Kanban', ['kanban']],
    ['Stand-ups', ['stand-up', 'stand-ups', 'stand ups', 'standups']],
    ['Sprint Planning', ['sprint planning', 'planning']],
    ['Demos', ['demos', 'demo']],
    ['Retrospectives', ['retrospectives', 'retrospective']],
    ['User Stories', ['user stories', 'user story']],
    ['Debugging', ['debugging', 'debug']],
    ['Testing', ['testing', 'test automation', 'unit testing', 'integration testing', 'tdd']],
    ['Peer Review', ['peer review', 'peer reviews', 'code review', 'code reviews', 'pair programming']],
    ['Documentation', ['documentation', 'documenting']],
    ['Deployment', ['deployment', 'deployments', 'deploy']],
    ['Configuration', ['configuration', 'configurations']],
    ['CI/CD', ['ci/cd', 'cicd', 'continuous integration', 'continuous delivery']],
    ['Docker', ['docker']],
    ['Kubernetes', ['kubernetes', 'k8s']],
    ['Infrastructure as Code', ['infrastructure as code', 'iac']],
    ['DevOps Practices', ['devops']],
    ['AWS CDK', ['aws cdk']],
    ['Datadog', ['datadog']],
    ['CloudWatch', ['cloudwatch']],
    ['Microservices', ['microservices', 'microservice architecture']],
    ['Serverless', ['serverless']],
    ['Problem Solving', ['problem solving', 'problem-solving']],
  ],
};

export const SOFT_SKILL_TAXONOMY = [
  ['Team Player', ['team player']],
  ['Collaboration', ['collaborating', 'collaboration', 'work across teams', 'work closely with', 'work with others', 'learning from others']],
  ['Communication', ['communicating clearly', 'communicate clearly', 'communication', 'technical and non-technical stakeholders', 'technical and business stakeholders']],
  ['Curiosity', ['curious', 'curiosity', 'inquisitive', 'understanding the why']],
  ['Proactivity', ['proactive', 'speak up early', 'follow through']],
  ['Customer Mindset', ['customer-minded', 'customer minded', 'real environments', 'works reliably']],
  ['Adaptability', ['adaptability', 'adaptable']],
  ['Ownership', ['ownership', 'accountability', 'take ownership']],
  ['Willingness to Learn', ['eager to learn', 'willingness to learn', 'learn and grow', 'growth mindset']],
];
