export const TECHNICAL_SKILL_FAMILIES = {
  softwareDevelopment: [
    ['C#', ['c#', 'c sharp']],
    ['.NET', ['.net', 'dotnet', 'dot net']],
    ['ASP.NET', ['asp.net', 'asp net']],
    ['MVC', ['mvc', 'model-view-controller']],
    ['JavaScript', ['javascript', 'js']],
    ['TypeScript', ['typescript', 'ts']],
    ['HTML', ['html']],
    ['CSS', ['css']],
    ['React', ['react', 'reactjs', 'react.js']],
    ['Node.js', ['node.js', 'node js', 'node']],
    ['Java', ['java']],
    ['Python', ['python']],
    ['REST APIs', ['rest api', 'rest apis', 'restful api', 'restful apis']],
    ['GraphQL', ['graphql']],
    ['GitHub', ['github']],
    ['Git', ['git']],
    ['WPF', ['wpf']],
  ],
  data: [
    ['SQL', ['sql', 'structured query language']],
    ['PostgreSQL', ['postgresql', 'postgres']],
    ['MySQL', ['mysql']],
    ['Excel', ['excel']],
    ['Power BI', ['power bi', 'powerbi']],
    ['Tableau', ['tableau']],
    ['Data Cleaning', ['data cleaning', 'data cleansing']],
    ['Data Transformation', ['data transformation', 'data wrangling']],
    ['ETL', ['etl']],
    ['Dashboarding', ['dashboarding', 'dashboards']],
    ['Reporting', ['reporting']],
    ['Statistics', ['statistics', 'statistical analysis']],
    ['Regression', ['regression']],
    ['Clustering', ['clustering']],
    ['Classification', ['classification']],
    ['Pandas', ['pandas']],
    ['NumPy', ['numpy']],
    ['Spark', ['spark', 'apache spark']],
    ['Airflow', ['airflow', 'apache airflow']],
    ['dbt', ['dbt']],
  ],
  aiMl: [
    ['Machine Learning', ['machine learning', 'ml']],
    ['Deep Learning', ['deep learning']],
    ['PyTorch', ['pytorch']],
    ['TensorFlow', ['tensorflow']],
    ['LLM', ['llm', 'large language model', 'large language models']],
    ['Prompt Engineering', ['prompt engineering']],
    ['RAG', ['rag', 'retrieval augmented generation']],
    ['Embeddings', ['embedding', 'embeddings']],
    ['Vector Search', ['vector search', 'vector database']],
    ['Semantic Retrieval', ['semantic retrieval']],
    ['NLP', ['nlp', 'natural language processing']],
    ['Model Deployment', ['model deployment', 'model serving']],
    ['Model Evaluation', ['model evaluation']],
    ['Feature Engineering', ['feature engineering']],
    ['MLOps', ['mlops']],
    ['Fine-tuning', ['fine tuning', 'fine-tuning']],
  ],
  itInfrastructure: [
    ['Windows Server', ['windows server']],
    ['Linux', ['linux']],
    ['Active Directory', ['active directory']],
    ['Networking', ['networking', 'tcp/ip', 'dns', 'dhcp', 'routing', 'switching']],
    ['AWS', ['aws', 'amazon web services']],
    ['Azure', ['azure']],
    ['GCP', ['gcp', 'google cloud']],
    ['Cloud Infrastructure', ['cloud infrastructure', 'cloud']],
    ['Troubleshooting', ['troubleshooting']],
    ['Incident Management', ['incident management']],
    ['Cybersecurity', ['cybersecurity', 'security monitoring']],
    ['Access Control', ['access control', 'iam']],
    ['VPN', ['vpn']],
    ['Firewalls', ['firewalls', 'firewall']],
    ['Ticketing Systems', ['ticketing system', 'ticketing systems', 'service desk']],
  ],
  commonEngineering: [
    ['Agile', ['agile']],
    ['Scrum', ['scrum']],
    ['Kanban', ['kanban']],
    ['Stand-ups', ['stand-up', 'stand-ups', 'stand ups', 'standups']],
    ['Sprint Planning', ['sprint planning', 'planning']],
    ['Demos', ['demos', 'demo']],
    ['Retrospectives', ['retrospectives', 'retrospective']],
    ['User Stories', ['user stories', 'user story']],
    ['Debugging', ['debugging', 'debug']],
    ['Testing', ['testing', 'test automation', 'unit testing', 'integration testing']],
    ['Peer Review', ['peer review', 'peer reviews', 'code review', 'code reviews']],
    ['Documentation', ['documentation', 'documenting']],
    ['Deployment', ['deployment', 'deployments', 'deploy']],
    ['Configuration', ['configuration', 'configurations']],
    ['CI/CD', ['ci/cd', 'cicd', 'continuous integration', 'continuous delivery']],
    ['Docker', ['docker']],
    ['Kubernetes', ['kubernetes', 'k8s']],
    ['Problem Solving', ['problem solving', 'problem-solving']],
  ],
};

export const SOFT_SKILL_TAXONOMY = [
  ['Team Player', ['team player']],
  ['Collaboration', ['collaborating', 'collaboration', 'work with others', 'learning from others']],
  ['Communication', ['communicating clearly', 'communication', 'writing notes', 'asking questions', 'sharing progress']],
  ['Curiosity', ['curious', 'curiosity', 'understanding the why']],
  ['Proactivity', ['proactive', 'speak up early', 'follow through']],
  ['Customer Mindset', ['customer-minded', 'customer minded', 'real environments', 'works reliably']],
  ['Adaptability', ['adaptability', 'adaptable']],
  ['Ownership', ['ownership', 'accountability']],
  ['Willingness to Learn', ['eager to learn', 'willingness to learn', 'learn and grow', 'growth mindset']],
];
