export const SECTION_HEADING_RULES = [
  {
    type: 'responsibilities',
    patterns: [
      /^what this role does:?$/i,
      /^what you'll be doing:?$/i,
      /^what you’ll be doing:?$/i,
      /^what you will be doing:?$/i,
      /^what you'll do:?$/i,
      /^what you will do:?$/i,
      /^responsibilities:?$/i,
      /^key responsibilities:?$/i,
      /^primary responsibilities:?$/i,
      /^the role:?$/i,
      /^about the role:?$/i,
      /^a day in the life:?$/i,
      /^you will:?$/i,
      /^duties:?$/i,
      /^your responsibilities:?$/i,
      /^position description:?$/i,
    ],
  },
  {
    type: 'qualifications',
    patterns: [
      /^core requirements:?$/i,
      /^bonus requirements:?$/i,
      /^what we're looking for:?$/i,
      /^what we’re looking for:?$/i,
      /^what we are looking for:?$/i,
      /^what you'll bring:?$/i,
      /^what you’ll bring:?$/i,
      /^what you bring:?$/i,
      /^you'll bring:?$/i,
      /^you’ll bring:?$/i,
      /^to get this all done, we’d like you to have:?$/i,
      /^to get this all done, we'd like you to have:?$/i,
      /^we’d love it if you also have:?$/i,
      /^we'd love it if you also have:?$/i,
      /^qualifications:?$/i,
      /^requirements:?$/i,
      /^experience and skills:?$/i,
      /^about you:?$/i,
      /^who we're looking for:?$/i,
      /^who we’re looking for:?$/i,
      /^the tech stack:?$/i,
      /^mindset & approach:?$/i,
      /^ōu pūkenga.*$/i,
      /^ngā pūkenga.*$/i,
    ],
  },
  {
    type: 'softSkillPersona',
    patterns: [
      /^you'll do well here if you're/i,
      /^you’ll do well here if you’re/i,
      /^success in this role$/i,
      /^who you are:?$/i,
      /^ideal candidate:?$/i,
      /^personal attributes:?$/i,
      /^purpose of the role:?$/i,
    ],
  },
  {
    type: 'benefits',
    patterns: [/^why join us!?$/i, /^benefits:?$/i, /^what we offer:?$/i, /^why work with us:?$/i, /^what's in it for you\??$/i, /^what’s in it for you\??$/i, /^why this role:?$/i, /^nā mātou te rourou.*$/i],
  },
  {
    type: 'companyContext',
    patterns: [/^job overview:?$/i, /^about us:?$/i, /^about .+$/i, /^company overview:?$/i, /^about flowingly:?$/i, /^he kōrero mō mātou.*$/i],
  },
  {
    type: 'applicationInstructions',
    patterns: [/^how to apply:?$/i, /^application process:?$/i, /^apply now:?$/i, /^application notes:?$/i, /^next steps:?$/i, /^employer questions:?$/i, /^me pēhea te tono.*$/i, /^kua rite, kia rite.*$/i],
  },
];

export const SECTION_TYPE_ORDER = [
  'introduction',
  'responsibilities',
  'qualifications',
  'softSkillPersona',
  'benefits',
  'companyContext',
  'applicationInstructions',
];
