import {
  AI_DELIVERY_SIGNAL_TAXONOMY,
  ML_SIGNAL_ALIASES,
  QUESTION_CATALOG_SEED,
} from '../../data/questionCatalogSeed2026_1.js';
import { QUESTION_CATALOG_REVIEW } from '../../data/questionCatalogReview2026_1.js';
import { ensureArray } from '../../utils/commonHelpers.js';

const formatCodeValues = (values = []) => (
  ensureArray(values).length
    ? ensureArray(values).map((value) => `\`${value}\``).join(', ')
    : '_none_'
);

const formatSources = (sources = []) => (
  ensureArray(sources).length
    ? ensureArray(sources).map((source, index) => `[source ${index + 1}](${source})`).join(', ')
    : '_none_'
);

const formatBooleanGates = (roleEligibility = {}) => {
  const enabledGates = [
    ['requiresExplicitAiDelivery', roleEligibility.requiresExplicitAiDelivery],
    ['requiresAiOrDigitalSignal', roleEligibility.requiresAiOrDigitalSignal],
    ['requiresMlSignal', roleEligibility.requiresMlSignal],
  ]
    .filter(([, enabled]) => enabled)
    .map(([name]) => name);
  return formatCodeValues(enabledGates);
};

const formatPromptVariants = (promptVariants = []) => ensureArray(promptVariants)
  .map((variant) => [
    `- **${variant.id}:** ${variant.text}`,
    `  - Target levels: ${formatCodeValues(variant.targetLevels)}`,
  ].join('\n'))
  .join('\n');

const renderCatalogItem = (item, index, reviewRecord = {}) => [
  `### ${index + 1}. \`${item.catalogQuestionId}\``,
  '',
  `- Family / type / competency: \`${item.questionFamily}\` / \`${item.questionType}\` / \`${item.competency}\``,
  `- Category: \`${item.category}\``,
  `- Eligible role families: ${formatCodeValues(item.roleEligibility?.roleFamilies)}`,
  `- Required candidate signals: ${formatCodeValues(item.roleEligibility?.requiredCandidateSignals)}`,
  `- Boolean eligibility gates: ${formatBooleanGates(item.roleEligibility)}`,
  `- Selection policy: min \`${item.selectionPolicy?.minAsked ?? 0}\`, max \`${item.selectionPolicy?.maxAsked ?? 0}\`, reservation priority \`${item.selectionPolicy?.reservationPriority ?? 0}\``,
  `- Expected answer signals: ${formatCodeValues(item.expectedSignals)}`,
  `- Report dimensions: ${formatCodeValues(item.reportDimensions)}`,
  `- Ambiguity mode: \`${item.ambiguityPolicy?.mode || 'none'}\``,
  '',
  '**Exact candidate wording by level**',
  '',
  formatPromptVariants(item.promptVariants),
  '',
  '**Do not select when**',
  '',
  ensureArray(item.notEligibleExamples).length
    ? ensureArray(item.notEligibleExamples).map((example) => `- ${example}`).join('\n')
    : '- No additional counterexample is configured beyond the eligibility fields above.',
  '',
  `**Research basis:** frequency \`${item.researchBasis?.frequencyBand || 'unspecified'}\`; reviewed \`${item.researchBasis?.reviewedAt || 'unspecified'}\`; ${formatSources(item.researchBasis?.sources)}`,
  '',
  reviewRecord.decision === 'approved'
    && ensureArray(reviewRecord.reviewedCatalogQuestionIds).includes(item.catalogQuestionId)
    ? '**Owner review:** [x] approve  [ ] revise  [ ] remove'
    : '**Owner review:** [ ] approve  [ ] revise  [ ] remove',
  '',
].join('\n');

const renderTaxonomyEntry = (entry, index, reviewRecord = {}) => [
  `### ${index + 1}. \`${entry.canonicalKey}\``,
  '',
  `- Signal family / strength: \`${entry.signalFamily}\` / \`${entry.strength}\``,
  `- Lifecycle / reviewed: \`${entry.lifecycle}\` / \`${entry.lastReviewedAt}\``,
  `- Aliases: ${formatCodeValues(entry.aliases)}`,
  `- Sources: ${formatSources(entry.sources)}`,
  '- Every alias above inherits the same lifecycle, review date, and sources through `aliasGovernance`.',
  '',
  reviewRecord.decision === 'approved'
    ? '**Owner review:** [x] approve  [ ] revise  [ ] remove'
    : '**Owner review:** [ ] approve  [ ] revise  [ ] remove',
  '',
].join('\n');

export const renderQuestionCatalogReviewMarkdown = ({
  catalogItems = QUESTION_CATALOG_SEED,
  aiDeliverySignalTaxonomy = AI_DELIVERY_SIGNAL_TAXONOMY,
  mlSignalAliases = ML_SIGNAL_ALIASES,
  reviewRecord = QUESTION_CATALOG_REVIEW,
} = {}) => [
  '# CP1 Full Human Review — Question Catalog `2026.1`',
  '',
  '> Generated from the governed source. Do not edit this file directly; update the source and regenerate it.',
  '',
  `Review decision: **${reviewRecord.decision}**`,
  `Reviewer: \`${reviewRecord.reviewer || 'not_recorded'}\``,
  `Decided at: \`${reviewRecord.decidedAt || 'not_recorded'}\``,
  `Candidate governance digest: \`${reviewRecord.candidateCatalogDigest}\``,
  `Approved governance digest: \`${reviewRecord.approvedCatalogDigest || 'not_approved'}\``,
  `Decision reason: ${reviewRecord.decisionReason || 'not recorded'}`,
  `Catalog items: **${catalogItems.length}**`,
  `AI-delivery taxonomy entries: **${aiDeliverySignalTaxonomy.length}**`,
  `ML signal aliases: **${mlSignalAliases.length}**`,
  '',
  'Digest scope:',
  '',
  ...ensureArray(reviewRecord.governanceScope).map((scope) => `- \`${scope}\``),
  '',
  'Approval is valid only for this exact digest. The digest covers the question items, AI-delivery taxonomy, and ML aliases shown below.',
  '',
  'Use the compact [CP1 decision sheet](./cp1-2026.1-catalog-review.md) to record the final decision after reviewing this generated detail.',
  '',
  '## Question catalog items',
  '',
  ...ensureArray(catalogItems).map((item, index) => renderCatalogItem(item, index, reviewRecord)),
  '## AI-delivery signal taxonomy',
  '',
  'A single provider name is not automatically an explicit AI-delivery signal. The resolver uses governed signal strength and family combinations.',
  '',
  ...ensureArray(aiDeliverySignalTaxonomy).map((entry, index) => renderTaxonomyEntry(entry, index, reviewRecord)),
  '## ML signal aliases',
  '',
  formatCodeValues(mlSignalAliases),
  '',
  reviewRecord.decision === 'approved'
    ? '**Owner review:** [x] approve  [ ] revise  [ ] remove aliases'
    : '**Owner review:** [ ] approve  [ ] revise  [ ] remove aliases',
  '',
  '## Final decision boundary',
  '',
  'Reviewing this artifact does not activate the database catalog. Activation still requires an approved review record with the same version, complete item ID set, reviewer identity, decision date, decision reason, and matching governance digest.',
  '',
].join('\n');
