export const AGENT_DECISION_TYPES = {
  BUILD_CONTEXT: 'BUILD_CONTEXT',
  SELECT_ACTION: 'SELECT_ACTION',
  EXECUTE_ACTION: 'EXECUTE_ACTION',
  UPDATE_MEMORY: 'UPDATE_MEMORY',
  FINALIZE_OUTPUT: 'FINALIZE_OUTPUT',
};
