export const AGENT_ACTION_TYPES = {
  RETRIEVE_EVIDENCE: 'RETRIEVE_EVIDENCE',
  ASK_POOL_QUESTION: 'ASK_POOL_QUESTION',
  ASK_RETRIEVED_QUESTION: 'ASK_RETRIEVED_QUESTION',
  ASK_PROBING_QUESTION: 'ASK_PROBING_QUESTION',
  ASK_VALIDATION_QUESTION: 'ASK_VALIDATION_QUESTION',
  SWITCH_TOPIC: 'SWITCH_TOPIC',
  WRAP_STAGE: 'WRAP_STAGE',
  GENERATE_REPORT_DRAFT: 'GENERATE_REPORT_DRAFT',
  QA_REPORT: 'QA_REPORT',
};
