export const RETRIEVAL_OBJECTIVES = {
  BOOTSTRAP_INTERVIEW_CONTEXT: 'BOOTSTRAP_INTERVIEW_CONTEXT',
  VALIDATE_CANDIDATE_CLAIM: 'VALIDATE_CANDIDATE_CLAIM',
  FIND_ROLE_SPECIFIC_QUESTION: 'FIND_ROLE_SPECIFIC_QUESTION',
  COLLECT_REPORT_EVIDENCE: 'COLLECT_REPORT_EVIDENCE',
  COVER_UNASKED_REQUIREMENT: 'COVER_UNASKED_REQUIREMENT',
};
